import json
import requests
import streamlit as st


def send_slack(alert_payload: dict) -> bool:
    """
    Sends a Strategic Intelligence alert to Slack using Block Kit.
    Webhook is securely loaded from Streamlit Secrets.
    """

    webhook_url = st.secrets.get("SLACK_WEBHOOK_URL")

    if not webhook_url:
        return False

    try:
        text = alert_payload.get("text", "").strip()

        # -------- Block Kit Construction --------
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🚨 STRATEGIC INTELLIGENCE ALERT",
                    "emoji": True
                }
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": text.split("--- Executive Summary ---")[0]
                }
            },
            {"type": "divider"},
        ]

        # -------- Executive Summary Parsing --------
        if "--- Executive Summary ---" in text:
            summary_part = text.split("--- Executive Summary ---")[1]

            if "--- Strategy Insight ---" in summary_part:
                summary_text, strategy_text = summary_part.split("--- Strategy Insight ---")
            else:
                summary_text = summary_part
                strategy_text = ""

            summary_lines = [
                line.replace("•", "*")
                for line in summary_text.split("\n")
                if line.strip().startswith("•")
            ]

            if summary_lines:
                blocks.append({
                    "type": "section",
                    "fields": [
                        {"type": "mrkdwn", "text": line}
                        for line in summary_lines
                    ]
                })

            blocks.append({"type": "divider"})

            if strategy_text.strip():
                blocks.append({
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Strategy Insight*\n{strategy_text.strip()}"
                    }
                })

        blocks.append({
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "Generated by Real-Time Market Intelligence Platform · AI-Assisted Decision Support"
                }
            ]
        })

        payload = {"blocks": blocks}

        response = requests.post(
            webhook_url,
            data=json.dumps(payload),
            headers={"Content-Type": "application/json"},
            timeout=10
        )

        return response.status_code == 200

    except Exception:
        return False
